albef_pretrained: 'logs/pretrained/ALBEF.pth'
vit_pretrained: 'logs/pretrained/pass_vit_base_full.pth'
batch_size: 64           # 默认值，命令行覆盖为128
fp16: True
height: 224
width: 224
epochs: 80              # 修改为80个epoch
lr: 0.0003
milestones: [25, 50]    # 调整为25和50，适配80个epoch
optimizer: 'Adam'
scheduler: 'step_lr'
warmup_step: 100        # 保持100，约1个epoch
weight_decay: 0.0005
workers: 0              # Windows默认
json_file: 'CUHK-PEDES/caption_all.json'
bert_base_path: 'reid/bert-base-uncased'
print_freq: 50
save_freq: 10           # 每10个epoch保存一次，共保存8次
logs_dir: 'logs'