albef_pretrained: 'logs/pretrained/ALBEF.pth'
vit_pretrained: 'logs/pretrained/pass_vit_base_full.pth'
batch_size: 32
fp16: True
height: 224  # ViT 要求 224x224
width: 224   # ViT 要求 224x224
epochs: 20   # 替换 iters
lr: 0.00035
milestones: [ 7, 14 ]  # 调整为 epoch 单位，假设每 7 个 epoch 下降一次
optimizer: 'Adam'
scheduler: 'step_lr'
warmup_step: 1000
weight_decay: 0.0005
workers: 4
json_file: 'cuhk_pedes/annotations/annotations.json'  # 修正路径，去掉 data/
bert_base_path: 'reid/bert-base-uncased'  # 改为相对路径
print_freq: 50
save_freq: 5
logs_dir: 'logs'  # 添加 logs_dir，与 train_joint.py 一致